Repository aredn/aredn_ar71xx, pull requests merged in 2018-08, with the labels that each got.

#101 bugfix: node description not saving properly
  files/etc/config.mesh/_setup
  files/etc/config.mesh/_setup.default
  files/etc/config.mesh/system
  files/www/cgi-bin/perlfunc.pm
  files/www/cgi-bin/setup
Labels: bug

#105 bugfix: upgrade iperf to iperf3
  configs/common.config
  patches/709-iperf-fw-restart.patch
Labels: bug, enhancement

#113 ci: make the make -jX parameter configurable
  .circleci/config.yml
Labels: build system enhancement

#117 build: move patch process after feeds update and clean up warning
  Makefile
Labels: build system enhancement

#118 build: fix luasrcdiet-luci Makefile
  patches/200-luasrcdiet-luci-build.patch
  patches/series
Labels: bug, build system enhancement

#121 update about.html page content
  files/www/about.html
Labels: enhancement

#128 bugfix: correct port order on airrouter
  patches/708-define-aredn-vlans.patch
Labels: bug

#136 bugfix: /tmp/hosts dir is missing
  patches/100-dnsmasq-upgrade.patch
Labels: bug

#139 Revert "bugfix: /tmp/hosts dir is missing (#136)"
  patches/100-dnsmasq-upgrade.patch
Labels: invalid

#150 build: add missing ubiquiti loco-m image to the build output
  configs/ar71xx-generic.config
Labels: bug
