Repository aredn/aredn_ar71xx, pull requests merged in 2018-07, with the labels that each got.

#52 build: Update final image names for CircleCI automation
  Makefile
  configs/common.config
  scripts/tests/postbuild/700-imagename.sh
Labels: build system enhancement

#50 circleci: add workflow to build/deploy nightly snapshots at 2100UTC
  .circleci/config.yml
Labels: build system enhancement

#58 bugfix: signal charts drop-down list (fixes #48)
  files/usr/lib/lua/aredn/utils.lua
  files/usr/local/bin/snrlog
Labels: bug

#60 circleci: add proper dependencies to control order of workflow exec
  .circleci/config.yml
Labels: build system enhancement

#63 circleci: correct proper targets directory structure
  .circleci/config.yml
Labels: build system enhancement

#74 bugfix: use new nslookup format (fixes #48)
  files/usr/lib/lua/aredn/utils.lua
Labels: bug

#73 Support more direct hosts
  files/www/cgi-bin/setup
Labels: enhancement

#77 feature: nodename field on setup page is too small
  files/www/cgi-bin/setup
Labels: enhancement

#78 Added the Nodes locally hosted service listing to sysinfo.json
  files/www/cgi-bin/sysinfo.json
Labels: enhancement

#80 Update contributors file
  CONTRIBUTORS
Labels: enhancement

#79 Add Node description to status (and setup) pages
  files/www/cgi-bin/setup
  files/www/cgi-bin/status
  files/www/cgi-bin/ucifunc.pm
Labels: enhancement
