Repository aredn/aredn_ar71xx, pull requests merged in 2019-01, with the labels that each got.

#324 build: set feeds to aredn_packages develop branch
  feeds.conf
Labels: build system enhancement

#342 feature: add sounds to realtime signal page
  files/www/cgi-bin/signal
Labels: enhancement

#343 bugfix: new settings will now show after a conditional setting (advancedconfig page)
  files/www/cgi-bin/advancedconfig
Labels: bug

#345 bugfix: correct issue when pushing sound "on" more than once
  files/www/cgi-bin/signal
Labels: bug

#347 feature: add pitch control to signal tone
  files/www/cgi-bin/signal
Labels: enhancement
